baseURL = "https://kimadeline.github.io/blog/"
languageCode = "en-us"
title = "An aptly named blog"
theme = "cactus"
copyright = "Kim-Adeline Miguel"

[params]
    colortheme = "dark" # dark, light, white, or classic

  # Home page settings
    description = """
ğŸ‘‹ Hello, and welcome! I am Kim-Adeline Miguel, and this is where I experiment with writing about code ğŸ§ª You can also find [talks](#projects) I've given further down this page.
    """
    mainSection = "posts"
  showProjectsList = true
  projectsUrl = "https://github.com/kimadeline/talk-proposals"

# Main menu which appears below site header.
[[menu.main]]
name = "ğŸ¡ Home"
url = "/"
weight = 1

[[menu.main]]
name = "ğŸ“š Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "ğŸ”– Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "ğŸ”® About"
url = "/about"
weight = 4

# Syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe= true
