baseURL = "http://example.org/"
languageCode = "en-us"
title = "An aptly named blog"
theme = "cactus"
copyright = "Kim-Adeline Miguel"

[params]
    colortheme = "dark" # dark, light, white, or classic
    description = """
    A description here
    """
    mainSection = "posts"

[markup.goldmark.renderer]
unsafe= true

# Main menu which appears below site header.
[[menu.main]]
name = "ğŸ¡ Home"
url = "/"
weight = 1

[[menu.main]]
name = "ğŸ“š Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "ğŸ”– Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "ğŸ”® About"
url = "/about"
weight = 4

# Syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
